Why Numpy:

For example:
* Much faster than other structures for many purpose
* Vectorized operations
* Often possible to avoid the need for for-loops
* Effective descriptive statistics and aggregationg/summarizing data
* Memory efficient
* Boolean indexing (we see this with Pandas more)
* Much more reasons...

Initializing Numpy Arrays can be done in many different ways, but often it is done by initializing it with a list

In [ ]:
import numpy as np
mylist=[1, 'Tommi', 2,5]
mylist

[1, 'Tommi', 2, 5]

In [ ]:
type(mylist)  # Type command is handy for checking you data's datatype

list

In [ ]:
# With Numpy, we usually have numbers as elements for the ndarray
myarr = np.array([1, 5, 4, 2])
myarr

array([1, 5, 4, 2])

In [ ]:
type(myarr)

numpy.ndarray

# Speed tests for numpy ndarrays and for regular list arrays

Note! for two lists, list_1 and list_2 the +-sign is not calculating the lists component by component but is catenating two strings

In [1]:
import numpy as np


In [2]:
list_1 = [1, 2, 3]
list_2 = [1, 2, 3]

In [3]:
list_1 + list_2

[1, 2, 3, 1, 2, 3]

Let's make this bit more interresting and initialize two lists and two ndarrays with really big number of values and then
see how long does it take for them sum the values up <ins>component wise</ins>

In [4]:
list_1 = list(range(100000000))
list_2 = list(range(100000000))

In [5]:
print(list_1[:5])
print(list_2[:5])

[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]


In [6]:
ndarray_1 = np.asarray(list_1)
ndarray_2 = np.asarray(list_2)

In [7]:
print(ndarray_1[:5])
print(ndarray_2[:5])

[0 1 2 3 4]
[0 1 2 3 4]


In [ ]:
# Now summing the values of the two list component wise
list_3 =[]

for i in list_1:
    list_3.append(list_1[i] + list_2[i])

In [ ]:
list_3[:5]

[0, 2, 4, 6, 8]

In [ ]:
ndarray_3=ndarray_1 + ndarray_2

In [ ]:
ndarray_3[:5]

array([0, 2, 4, 6, 8])